---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: >
  Handles my GumRoad post purchase workflow.

Resources:
    GumRoadPingHandler:
      Type: AWS::Serverless::Function
      Properties:
          CodeUri: dist/
          Handler: handler.handler
          Runtime: python3.8
          Timeout: 29
          AutoPublishAlias: live
          DeploymentPreference:
              #Change to Canary10Percent5Minutes after developemnt
              Type: AllAtOnce
          MemorySize: 128
          Policies:
            - Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action: ssm:GetParameter
                  Resource: '*'
          Events:
            APIGateway:
              Type: Api
              Properties:
                Path: /
                Method: POST
